### ISSUE TITLE
Max BBFrame Length not correct

### ISSUE THREAD

**Issue by F5OEO** [daniestevez/dvb-gse#17]
https://github.com/daniestevez/dvb-gse/blob/d5025f003bc437c2525394381e3aad5e4a1f94a5/src/bbframe.rs#L16

The max len of a bbframe has been calculated with dvbs2-x extension. However, in dvbs2, fec 8/9 and fec 9/10 in longframe are respectively 57472 and 58192.

Fix by changing : const BBFRAME_MAX_LEN: usize = 7274;

**Comment by daniestevez** [comment]
Oh, I didn't realize that the DVB-S2 9/10 MODCOD has higher rate than those DVB-S2X MODCODs. I've just sent a PR that fixes this. I'll merge it when it passes the pipeline.
